// Generated by CoffeeScript 1.12.7-patch.2
(function() {
  var Browser;

  Browser = function(element) {
    var browser, container, controller, initialize, model, options, size, view;
    options = {
      shiny: false,
      knitr: false
    };
    size = {
      width: 800,
      height: 600
    };
    container = null;
    view = null;
    model = null;
    controller = KeyboardController(null);
    initialize = function() {
      options.shiny = typeof HTMLWidgets !== 'undefined' && HTMLWidgets.shinyMode;
      element = $(element);
      return container = $("<div>", {
        "class": "main-container"
      }).appendTo(element);
    };
    browser = function() {};
    browser.setData = function(raw) {
      model = DataSet(raw);
      view = TextTreeView(container, model);
      controller.setView(view);
      return view.refresh();
    };
    browser.setSize = function(width, height) {
      return size = {
        width: width,
        height: height
      };
    };
    browser.setOption = function(name, value) {};
    initialize();
    return browser;
  };

  window.Browser = Browser;

}).call(this);
