"use strict";

// Generated by CoffeeScript 2.3.1
(function () {
  // --- Browser ----------------------------------------------------------
  var Browser;

  Browser = function Browser(element) {
    var browser, container, controller, initialize, model, options, size, view;
    options = {
      shiny: false,
      knitr: false
    };
    size = {
      width: 800,
      height: 600
    };
    container = null;
    view = null;
    model = null;
    controller = KeyboardController(null);
    initialize = function initialize() {
      log.debug("");
      options.shiny = typeof HTMLWidgets !== 'undefined' && HTMLWidgets.shinyMode;
      element = $(element);
      return container = $("<div>", {
        class: "main-container"
      }).appendTo(element);
    };
    browser = function browser() {};
    browser.setData = function (raw) {
      log.debug("");
      model = DataSet(raw);
      view = TextTreeView(container, model);
      controller.setView(view);
      return view.refresh();
    };
    browser.setSize = function (width, height) {
      return size = {
        width: width,
        height: height
      };
    };
    browser.setOption = function (name, value) {};
    // TODO set option
    initialize();
    return browser;
  };

  // --- exports ----------------------------------------------------------
  window.Browser = Browser;
}).call(undefined);