// Generated by CoffeeScript 1.12.7-patch.2
(function() {
  var KeyboardController;

  KeyboardController = function(view) {
    var keyDown, keyboardController, translateKey;
    keyboardController = function() {};
    keyboardController.initialize = function() {
      return $(window).on('keydown', keyDown);
    };
    keyboardController.setView = function(newView) {
      return view = newView;
    };
    keyDown = function(e) {
      var key;
      key = translateKey(e);
      if (view && view.keyboardSignal.call(this, key)) {
        return e.preventDefault();
      }
    };
    translateKey = function(e) {
      var Codes, keyCode, ref;
      Codes = {
        13: "enter",
        37: "left",
        38: "up",
        39: "right",
        40: "down"
      };
      keyCode = (ref = e.originalEvent) != null ? ref.keyCode : void 0;
      if (keyCode in Codes) {
        return Codes[keyCode];
      }
      return null;
    };
    keyboardController.initialize();
    return keyboardController;
  };

  window.KeyboardController = KeyboardController;

}).call(this);
