// Generated by CoffeeScript 1.12.7-patch.2
(function() {
  var DataSet;

  DataSet = function(raw) {
    var dataset, stratified;
    dataset = function() {};
    stratified = function() {
      var stratify;
      stratify = d3.stratify().id(function(d) {
        return d.id;
      }).parentId(function(d) {
        var ref;
        if ((ref = d.parents) != null ? ref.length : void 0) {
          return d.parents[0];
        }
      });
      return stratify(raw);
    };
    dataset.traverseAsTree = function(f, root) {
      var strats, traverse;
      log.debug("traversing as tree");
      traverse = function(node, parent) {
        var child, i, len, ref, results;
        f(node.data, parent);
        if (node.children) {
          ref = node.children;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            child = ref[i];
            results.push(traverse(child, node.data));
          }
          return results;
        }
      };
      strats = stratified();
      console.log(strats.children[0]);
      return traverse(strats, root);
    };
    return dataset;
  };

  window.DataSet = DataSet;

}).call(this);
