// Generated by CoffeeScript 1.12.7-patch.2
(function() {
  var Log, Viewport, sign;

  Array.prototype.unique = function() {
    var i, key, output, ref, ref1, results, value;
    output = {};
    for (key = i = 0, ref = this.length; 0 <= ref ? i < ref : i > ref; key = 0 <= ref ? ++i : --i) {
      output[(ref1 = this[key].id) != null ? ref1 : this[key]] = this[key];
    }
    results = [];
    for (key in output) {
      value = output[key];
      results.push(value);
    }
    return results;
  };

  Array.prototype.min = function() {
    return this.reduce(function(a, b) {
      return Math.min(a, b);
    });
  };

  Array.prototype.max = function() {
    return this.reduce(function(a, b) {
      return Math.max(a, b);
    });
  };

  Array.prototype.remove = function(e) {
    return this.filter(function(el) {
      return el !== e;
    });
  };

  if (Math.sign === void 0) {
    sign = function(x) {
      if (x < 0) {
        return -1;
      } else {
        return 1;
      }
    };
  } else {
    sign = Math.sign;
  }

  Log = function() {
    var callerName, enabled, log, showMessage;
    enabled = false;
    callerName = function() {
      var re, res, st;
      re = /([^(]+)@|at ([^(]+) \(/gm;
      st = new Error().stack;
      re.exec(st);
      re.exec(st);
      re.exec(st);
      res = re.exec(st);
      if (!res) {
        return "unknown";
      }
      return res[1] || res[2];
    };
    showMessage = function(level, message) {
      var caller;
      if (!enabled) {
        return;
      }
      caller = callerName();
      return console.log(level + " " + caller + ": " + message);
    };
    log = function() {};
    log.debug = function(message) {
      return showMessage("DEBUG", message);
    };
    log.info = function(message) {
      return showMessage("INFO ", message);
    };
    log.enable = function(onoff) {
      return enabled = onoff;
    };
    return log;
  };

  Viewport = function(selection) {
    var viewport;
    viewport = function() {};
    viewport.size = function() {
      var h, w;
      w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
      h = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
      w = Math.min(w, $(selection).width());
      h = Math.min(h, $(selection).height());
      return {
        width: w,
        height: h
      };
    };
    return viewport;
  };

  window.log = Log();

}).call(this);
