"use strict";

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

// Generated by CoffeeScript 2.3.1
(function () {
  var Log, Viewport, isShiny, send2Shiny, sign, tryCatch;

  Array.prototype.unique = function () {
    var i, key, output, ref, ref1, results, value;
    output = {};
    for (key = i = 0, ref = this.length; 0 <= ref ? i < ref : i > ref; key = 0 <= ref ? ++i : --i) {
      output[(ref1 = this[key].id) != null ? ref1 : this[key]] = this[key];
    }
    results = [];
    for (key in output) {
      value = output[key];
      results.push(value);
    }
    return results;
  };

  Array.prototype.min = function () {
    return this.reduce(function (a, b) {
      return Math.min(a, b);
    });
  };

  Array.prototype.max = function () {
    return this.reduce(function (a, b) {
      return Math.max(a, b);
    });
  };

  Array.prototype.remove = function (e) {
    return this.filter(function (el) {
      return el !== e;
    });
  };

  Array.prototype.last = function () {
    return this[this.length - 1];
  };

  if (Math.sign === void 0) {
    sign = function sign(x) {
      if (x < 0) {
        return -1;
      } else {
        return 1;
      }
    };
  } else {
    sign = Math.sign;
  }

  // --- simple logger ----------------------------------------------------
  Log = function Log() {
    var callerName, enabled, log, showMessage;
    enabled = false;
    callerName = function callerName() {
      var re, res, st;
      re = /([^(]+)@|at ([^(]+) \(/gm;
      st = new Error().stack;
      re.exec(st); // skip 1st line
      re.exec(st); // skip 2nd line
      re.exec(st); // skip 3rd line
      res = re.exec(st);
      if (!res) {
        return "unknown";
      }
      return res[1] || res[2];
    };
    showMessage = function showMessage(level, message) {
      var caller;
      if (!enabled) {
        return;
      }
      caller = callerName();
      return console.log(level + " " + caller + ": " + message);
    };
    log = function log() {};
    log.debug = function (message) {
      return showMessage("DEBUG", message);
    };
    log.info = function (message) {
      return showMessage("INFO ", message);
    };
    log.enable = function (onoff) {
      return enabled = onoff;
    };
    return log;
  };

  Viewport = function Viewport(selection) {
    var viewport;
    viewport = function viewport() {};
    viewport.size = function () {
      var h, w;
      // actual viewport; in R Studio, when running as AddIn, this is somehow
      // distorted and reports size larger than the actual viewport area
      w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
      h = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
      // thus, we compare it with the size of the enclosing HTML element and
      // choose whatever is smaller
      w = Math.min(w, $(selection).width());
      h = Math.min(h, $(selection).height());
      return {
        width: w,
        height: h
      };
    };
    return viewport;
  };

  // --- Shiny ------------------------------------------------------------
  isShiny = function isShiny() {
    return (typeof HTMLWidgets === "undefined" ? "undefined" : _typeof(HTMLWidgets)) === !'undefined' && HTMLWidgets.shinyMode;
  };

  send2Shiny = function send2Shiny(inputName, message) {
    if (isShiny) {
      return Shiny.onInputChange(inputName, message);
    } else {
      return alert(message);
    }
  };

  // --- exceptions in callbacks ------------------------------------------
  tryCatch = function tryCatch(fun) {
    var err;
    try {
      for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
        args[_key - 1] = arguments[_key];
      }

      return fun.apply(undefined, args);
    } catch (error) {
      err = error;
      return send2Shiny('exception', err.message);
    }
  };

  // --- exports ----------------------------------------------------------
  window.log = Log();

  window.isShiny = isShiny;

  window.send2Shiny = send2Shiny;

  window.tryCatch = tryCatch;
}).call(undefined);