// Generated by CoffeeScript 1.12.7-patch.2
(function() {
  var TextTreeView;

  TextTreeView = function(external, model) {
    var artifactDescription, container, flatView, listBasedView, selectArtifact, textTreeView;
    container = $('<div>', {
      "class": 'view'
    }).appendTo(external);
    textTreeView = function() {};
    textTreeView.refresh = function() {
      if (false) {
        return listBasedView();
      } else {
        return flatView();
      }
    };
    listBasedView = function() {
      var htmlChildren, htmlSelf, root, topUl, visit;
      visit = function(node, parent) {
        node.htmlSelf = $('<li>').appendTo(parent.htmlChildren);
        return node.htmlChildren = $('<ul>').appendTo(node.htmlSelf);
      };
      topUl = $('<ul>').appendTo(container);
      htmlSelf = $('<li>').appendTo(topUl);
      htmlChildren = $('<ul>').appendTo(htmlSelf);
      root = {
        htmlChildren: topUl
      };
      return model.traverseAsTree(visit, {
        htmlChildren: htmlChildren
      });
    };
    flatView = function() {
      var create;
      create = function(node, parent) {
        node.left = parent.left + 20;
        return node.element = $('<div>', {
          "class": 'flat-artifact'
        }).css({
          left: node.left
        }).on('click', node, selectArtifact).appendTo(container).append(artifactDescription(node));
      };
      return model.traverseAsTree(create, {
        left: 0
      });
    };
    artifactDescription = function(a) {
      var element;
      element = $("<div>").load($("#browser-1-attachment").attr("href"), null, function() {
        element.find(".name").text(a.name);
        element.find(".description").text(a.description);
        element.find("code").text(a.expression).each(function(i, block) {
          return hljs.highlightBlock(block);
        });
        return element.find('.code-block').addClass('invisible');
      });
      return element;
    };
    textTreeView.keyboardSignal = function(key) {
      if (key === 'enter') {
        container.find('.selected').find('.code-block').toggleClass('invisible');
        return true;
      }
    };
    selectArtifact = function(event) {
      container.find('.flat-artifact').removeClass('selected');
      return $(this).addClass('selected');
    };
    log.debug('created view');
    return textTreeView;
  };

  window.TextTreeView = TextTreeView;

}).call(this);
